-- PostgreSQL 17 history tables and triggers for the Exomiser app.
-- PostgreSQL counterpart of the history section of app.sql (SQLite). A column change
-- on users, individuals or analyses must update both files.
-- changed_at is naive UTC, like the app's datetime.utcnow columns.
-- analyses_history deliberately omits log and phenopacket_yaml (large fields).
-- No percent signs here: the migration script runs each section as one string.

-- ==== SECTION 1: TABLES ====

create table users_history (
    history_id bigint generated by default as identity primary key,
    operation varchar(10) not null,
    changed_at timestamp not null,
    id integer not null,
    email varchar(120),
    password_hash varchar(256),
    full_name varchar(120),
    is_active boolean,
    is_admin boolean,
    is_deleted boolean,
    deleted_at timestamp,
    created_at timestamp,
    updated_at timestamp
);
create index ix_users_history_id on users_history (id);

create table individuals_history (
    history_id bigint generated by default as identity primary key,
    operation varchar(10) not null,
    changed_at timestamp not null,
    id integer not null,
    identity varchar(50),
    full_name varchar(120),
    sex varchar(10),
    age_years integer,
    age_months integer,
    medical_history text,
    diagnosis varchar(255),
    vcf_filename varchar(255),
    vcf_file_path varchar(255),
    is_deleted boolean,
    deleted_at timestamp,
    created_by integer,
    updated_by integer,
    created_at timestamp,
    updated_at timestamp
);
create index ix_individuals_history_id on individuals_history (id);

create table analyses_history (
    history_id bigint generated by default as identity primary key,
    operation varchar(10) not null,
    changed_at timestamp not null,
    id integer not null,
    individual_id integer,
    hpo_terms text,
    name varchar(120),
    description text,
    genome_assembly varchar(10),
    analysis_mode varchar(50),
    frequency_threshold double precision,
    pathogenicity_threshold double precision,
    status varchar(20),
    output_html varchar(500),
    output_vcf varchar(500),
    started_at timestamp,
    completed_at timestamp,
    error_message text,
    is_deleted boolean,
    deleted_at timestamp,
    created_by integer,
    updated_by integer,
    created_at timestamp,
    updated_at timestamp
);
create index ix_analyses_history_id on analyses_history (id);

-- ==== SECTION 2: FUNCTIONS AND TRIGGERS ====

create function users_history_fn() returns trigger language plpgsql as $$
begin
    if TG_OP = 'DELETE' then
        insert into users_history (operation, changed_at, id, email, password_hash, full_name, is_active, is_admin, is_deleted, deleted_at, created_at, updated_at)
        values (TG_OP, now() at time zone 'utc', OLD.id, OLD.email, OLD.password_hash, OLD.full_name, OLD.is_active, OLD.is_admin, OLD.is_deleted, OLD.deleted_at, OLD.created_at, OLD.updated_at);
        return OLD;
    end if;
    insert into users_history (operation, changed_at, id, email, password_hash, full_name, is_active, is_admin, is_deleted, deleted_at, created_at, updated_at)
    values (TG_OP, now() at time zone 'utc', NEW.id, NEW.email, NEW.password_hash, NEW.full_name, NEW.is_active, NEW.is_admin, NEW.is_deleted, NEW.deleted_at, NEW.created_at, NEW.updated_at);
    return NEW;
end
$$;

create trigger users_history_insert after insert on users for each row execute function users_history_fn();
create trigger users_history_update after update on users for each row execute function users_history_fn();
create trigger users_history_delete after delete on users for each row execute function users_history_fn();

create function individuals_history_fn() returns trigger language plpgsql as $$
begin
    if TG_OP = 'DELETE' then
        insert into individuals_history (operation, changed_at, id, identity, full_name, sex, age_years, age_months, medical_history, diagnosis, vcf_filename, vcf_file_path, is_deleted, deleted_at, created_by, updated_by, created_at, updated_at)
        values (TG_OP, now() at time zone 'utc', OLD.id, OLD.identity, OLD.full_name, OLD.sex::text, OLD.age_years, OLD.age_months, OLD.medical_history, OLD.diagnosis, OLD.vcf_filename, OLD.vcf_file_path, OLD.is_deleted, OLD.deleted_at, OLD.created_by, OLD.updated_by, OLD.created_at, OLD.updated_at);
        return OLD;
    end if;
    insert into individuals_history (operation, changed_at, id, identity, full_name, sex, age_years, age_months, medical_history, diagnosis, vcf_filename, vcf_file_path, is_deleted, deleted_at, created_by, updated_by, created_at, updated_at)
    values (TG_OP, now() at time zone 'utc', NEW.id, NEW.identity, NEW.full_name, NEW.sex::text, NEW.age_years, NEW.age_months, NEW.medical_history, NEW.diagnosis, NEW.vcf_filename, NEW.vcf_file_path, NEW.is_deleted, NEW.deleted_at, NEW.created_by, NEW.updated_by, NEW.created_at, NEW.updated_at);
    return NEW;
end
$$;

create trigger individuals_history_insert after insert on individuals for each row execute function individuals_history_fn();
create trigger individuals_history_update after update on individuals for each row execute function individuals_history_fn();
create trigger individuals_history_delete after delete on individuals for each row execute function individuals_history_fn();

create function analyses_history_fn() returns trigger language plpgsql as $$
begin
    if TG_OP = 'DELETE' then
        insert into analyses_history (operation, changed_at, id, individual_id, hpo_terms, name, description, genome_assembly, analysis_mode, frequency_threshold, pathogenicity_threshold, status, output_html, output_vcf, started_at, completed_at, error_message, is_deleted, deleted_at, created_by, updated_by, created_at, updated_at)
        values (TG_OP, now() at time zone 'utc', OLD.id, OLD.individual_id, OLD.hpo_terms::text, OLD.name, OLD.description, OLD.genome_assembly::text, OLD.analysis_mode, OLD.frequency_threshold, OLD.pathogenicity_threshold, OLD.status::text, OLD.output_html, OLD.output_vcf, OLD.started_at, OLD.completed_at, OLD.error_message, OLD.is_deleted, OLD.deleted_at, OLD.created_by, OLD.updated_by, OLD.created_at, OLD.updated_at);
        return OLD;
    end if;
    insert into analyses_history (operation, changed_at, id, individual_id, hpo_terms, name, description, genome_assembly, analysis_mode, frequency_threshold, pathogenicity_threshold, status, output_html, output_vcf, started_at, completed_at, error_message, is_deleted, deleted_at, created_by, updated_by, created_at, updated_at)
    values (TG_OP, now() at time zone 'utc', NEW.id, NEW.individual_id, NEW.hpo_terms::text, NEW.name, NEW.description, NEW.genome_assembly::text, NEW.analysis_mode, NEW.frequency_threshold, NEW.pathogenicity_threshold, NEW.status::text, NEW.output_html, NEW.output_vcf, NEW.started_at, NEW.completed_at, NEW.error_message, NEW.is_deleted, NEW.deleted_at, NEW.created_by, NEW.updated_by, NEW.created_at, NEW.updated_at);
    return NEW;
end
$$;

create trigger analyses_history_insert after insert on analyses for each row execute function analyses_history_fn();
create trigger analyses_history_update after update on analyses for each row execute function analyses_history_fn();
create trigger analyses_history_delete after delete on analyses for each row execute function analyses_history_fn();
